### ISSUE TITLE
using pinia-plugin-persistedstate with js cookie

### ISSUE THREAD

**Issue by u007** [vikejs/vike-vue#140]
hi,

i realise when using js cookie, it does reflect on browser side calling to server as i can see the headers is set.
but it does not seems to show on server side when rendering.

cookie storage:
https://github.com/u007/vike-admin/blob/main/store/storage.cookie.ts

the pinia using it:
https://github.com/u007/vike-admin/blob/main/store/alert.ts

**Comment by u007** [comment]
on browser end: 
<img width="936" alt="Screenshot 2024-06-23 at 2 44 09 AM" src="https://github.com/vikejs/vike-vue/assets/388813/55655fcc-5135-400a-9b33-b11d7c4e89fb">

on server side:
<img width="549" alt="Screenshot 2024-06-23 at 2 44 33 AM" src="https://github.com/vikejs/vike-vue/assets/388813/ab1a2618-5d35-4cd2-8858-41201367786d">

**Comment by brillout** [comment]
Hydration errors are usually user land issues, and these 404 don't seem to be related.

Closing because it isn't clear from reading your post whether your issues are user land ones or vike-vue related.

On Vike's GitHub the expectation generally is that you follow https://brillout.github.io/rules, see https://vike.dev/faq#how-can-i-reach-out-for-help.

Feel free to re-create one new post per issue and only if you have confidence it's related to Vike / vike-vue.
