### ISSUE TITLE
vue query is doing double request

### ISSUE THREAD

**Issue by RGdevz** [vikejs/vike-vue#199]
I tried the vue query extension and I noticed that if you refresh a page its will first do the fetch on the server and then will do it again on client.

I did find a way to prevent this like this using the enabled argument
```javascript
const { isError, isPending, isFetching, data, error, suspense } = useQuery({
queryKey: ['key'],
enabled:usePageContext()._vueQueryInitialState == undefined,
...
 ```
 this way the fetch will happen only on the server on refresh and on the client on client side navigation.
 I don't know if it's the best fix but it works

**Comment by brillout** [comment]
@4350pChris WDYT?

**Comment by brillout** [comment]
@4350pChris I could reproduce with `examples/vue-query` the `fetchMovies()` function is indeed double called.

**Comment by 4350pChris** [comment]
@brillout My hunch is that this is because the order of hydrating the client and registering the plugin is switched. Have a look at these docs - https://tanstack.com/query/latest/docs/framework/vue/guides/ssr#using-vite-ssr

You can see that the client is hydrated **first** before installing the plugin.
We're doing it the other way around - `createVueApp` installs plugins by calling `onCreateApp`, while hydration happens in `onBeforeRenderClient`.
In `onRenderClient`, `createVueApp` is called before `onBeforeRenderClient`, causing hydration to happen after installing the plugin.

I'll check if this is the actual reason.

**Comment by 4350pChris** [comment]
Nevermind that, the reason is the following:

> Query instances via useQuery or useInfiniteQuery by default consider cached data as stale.

from https://tanstack.com/query/latest/docs/framework/vue/guides/important-defaults

So this is expected behavior. If you want queries not to refetch, you'll have to add `staleTime: 1000 * 60 * 5 // example for 5 minutes in ms` to `+queryClientConfig.ts`.

**Comment by brillout** [comment]
Makes sense, thank you! We should add some docs at https://github.com/vikejs/vike-vue/tree/main/packages/vike-vue-pinia#readme.

**Comment by brillout** [comment]
> We should add some docs at https://github.com/vikejs/vike-vue/tree/main/packages/vike-vue-pinia#readme.

In the meantime I've added a stale time to the example.

**Comment by RGdevz** [comment]
thanks for helping
